---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-compliance-operator
  namespace: compliance-operator-policies
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
